[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'postgresql']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'python -m pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build completed successfully"']

[start]
cmd = 'gunicorn wsgi:application --bind 0.0.0.0:$PORT --workers 4 --timeout 120'

[variables]
FLASK_ENV = 'production' 